---
title: "Data wrangling"
author: "Anne"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse) #install.packages("tidyverse")
```
```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect the data
gapminder #looks at all the data
head(gapminder) #give you the head (first 6 by default)
tail(gapminder, 10) #bottom 10, comma number if not default

#summary statistics
str(gapminder)
summary(gapminder)

install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #column names
dim(gapminder)#dimensions
ncol(gapminder)#number of columns
nrow(gapminder)#number of rows

#reverse enginere dim
c(nrow(gapminder), ncol(gapminder))

```
#Dplyr!
```{r}
#filter by rows
filter(gapminder,lifeExp<29)
filter(gapminder,country=="Mexico")
filter(gapminder,country%in%c("Mexico","Peru"))
filter(gapminder,country=="Mexico", year== 2002)
#find mean lifeExp of Sweden
sweden<- filter(gapminder, country=="Sweden")
sweden$lifeExp
mean(sweden$lifeExp)
```

```{r}
#select by columns
select(gapminder,year,lifeExp)#select only these columns
select(gapminder,-continent,-lifeExp) #- will exclude these columns
#use select and filter together
gap_cambodia <- filter(gapminder,country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia,-continent,-lifeExp)
gap_cambodia2
```

The Pipe operator will change your life
```{r}
gapminder%>%head(3)
#equivalent to 
head(gapminder,3)
#lets improve this with pipes!
gap_cambodia <- filter(gapminder, country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia,-continent, -lifeExp)

gap_cambodia <- gapminder%>%
  filter(country=="Cambodia") %>%
  select(-continent,-lifeExp)
gap_cambodia

```
#mutate adds new variables
```{r}
gapminder %>% 
  mutate(index=1:nrow(gapminder))

gapminder %>% 
  mutate(planet="Earth")

gapminder %>% 
  mutate(gdp=pop*gdpPercap)

#find the max gdpPercap of Egypt and Vietnam. Create new column
gapminder %>% 
  filter(country%in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  mutate(max_gdp=max(gdp))

#same as this
gapminder %>% 
filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  mutate(max_gdp=max(gdp))
#you can introduce new columns in the same section

```
## 'group_by() groups!
```{r}
##with mutate()
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap,
         max_gdp=max(gdp)) %>% 
  ungroup()

##with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  summarize(max_gdp=max(gdp)) %>% 
  ungroup()
```
##'arrange()' arranges columns
```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp=pop*gdpPercap) %>% 
  summarize(max_gdp=max(gdp)) %>% 
  ungroup() %>% 
  arrange(max_gdp)#could use desc(max_gdp) to rearrange order
```
##Joining data
```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() # 12

## create new variable that is only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007) 
gap_2007 %>% dim() # 142  

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
#another way to write
lj <- gap_2007 %>% 
  left_join(co2,by="country")

## explore
lj %>% dim() #142
lj %>% summary() # lots of NAs in the co2_2017 columm
lj %>% View() 

## right_join gap_2007 and co2
rj <- right_join(gap_2007, co2, by = "country")
#the same as , just different posions
lj2 <- left_join(co2,gap_2007, by ="country")
## explore
rj %>% dim() # 12
rj %>% summary()
rj %>% View() 

#is.na function to select them specificly 

```

